# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  ca_org3:
    image: mihongtech/mh-ca:$IMAGE_TAG
    environment:
      - CA_CFG_PATH=/etc/mihongtech/mh-ca-server/mh-ca-server-config.yaml
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'mh-ca-server start -b admin:adminpw -d'
    volumes:
      - ../mh-ca/org3:/etc/mihongtech/mh-ca-server
    container_name: ca_org3
