# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  consensus.example.com:
  commiter0.org1.example.com:
  commiter0.org2.example.com:

networks:
  test:

services:

  consensus.example.com:
    container_name: consensus.example.com
    image: mihongtech/mhchain-consensus:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=ConsensusMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/mihongtech/consensus/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/mihongtech/consensus/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/mihongtech/consensus/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/mihongtech/consensus/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/mihongtech/consensus/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/mihongtech/consensus/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/mihongtech/consensus/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/mihongtech/consensus/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/mihongtech/consensus/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/mihongtech/consensus/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/mihongtech/consensus/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    working_dir: /opt/gopath/src/github.com/mihongtech/mhchain
    command: consensus
    volumes:
        - ../system-genesis-block/genesis.block:/var/mihongtech/consensus/consensus.genesis.block
        - ../organizations/consensusOrganizations/example.com/consensuss/consensus.example.com/msp:/var/mihongtech/consensus/msp
        - ../organizations/consensusOrganizations/example.com/consensuss/consensus.example.com/tls/:/var/mihongtech/consensus/tls
        - consensus.example.com:/var/mihongtech/production/consensus
    ports:
      - 7050:7050
      - 7053:7053
    networks:
      - test

  commiter0.org1.example.com:
    container_name: commiter0.org1.example.com
    image: mihongtech/mhchain-commiter:$IMAGE_TAG
    environment:
      #Generic commiter variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the commiters
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CORE_CHAINCODE_BUILDER=${DOCKER_NS}/mhchain-ccenv:$IMAGE_TAG
      - CORE_CHAINCODE_GOLANG_RUNTIME=${DOCKER_NS}/mhchain-baseos:$IMAGE_TAG
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/mihongtech/mhchain/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/mihongtech/mhchain/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/mihongtech/mhchain/tls/ca.crt
      # Commiter specific variabes
      - CORE_PEER_ID=commiter0.org1.example.com
      - CORE_PEER_ADDRESS=commiter0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=commiter0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=commiter0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=commiter0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/commiterOrganizations/org1.example.com/commiters/commiter0.org1.example.com/msp:/etc/mihongtech/mhchain/msp
        - ../organizations/commiterOrganizations/org1.example.com/commiters/commiter0.org1.example.com/tls:/etc/mihongtech/mhchain/tls
        - commiter0.org1.example.com:/var/mihongtech/production
    working_dir: /opt/gopath/src/github.com/mihongtech/mhchain/commiter
    command: commiter node start
    ports:
      - 7051:7051
    networks:
      - test

  commiter0.org2.example.com:
    container_name: commiter0.org2.example.com
    image: mihongtech/mhchain-commiter:$IMAGE_TAG
    environment:
      #Generic commiter variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the commiters
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CORE_CHAINCODE_BUILDER=${DOCKER_NS}/mhchain-ccenv:$IMAGE_TAG
      - CORE_CHAINCODE_GOLANG_RUNTIME=${DOCKER_NS}/mhchain-baseos:$IMAGE_TAG
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/mihongtech/mhchain/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/mihongtech/mhchain/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/mihongtech/mhchain/tls/ca.crt
      # Commiter specific variabes
      - CORE_PEER_ID=commiter0.org2.example.com
      - CORE_PEER_ADDRESS=commiter0.org2.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=commiter0.org2.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=commiter0.org2.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=commiter0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/commiterOrganizations/org2.example.com/commiters/commiter0.org2.example.com/msp:/etc/mihongtech/mhchain/msp
        - ../organizations/commiterOrganizations/org2.example.com/commiters/commiter0.org2.example.com/tls:/etc/mihongtech/mhchain/tls
        - commiter0.org2.example.com:/var/mihongtech/production
    working_dir: /opt/gopath/src/github.com/mihongtech/mhchain/commiter
    command: commiter node start
    ports:
      - 9051:9051
    networks:
      - test
  
  cli:
    container_name: cli
    image: mihongtech/mhchain-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/mihongtech/mhchain/commiter
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/mihongtech/mhchain/commiter/organizations
        - ../scripts:/opt/gopath/src/github.com/mihongtech/mhchain/commiter/scripts/
    depends_on:
      - commiter0.org1.example.com
      - commiter0.org2.example.com
    networks:
      - test
